---
- name: install releaded packages
  apt:
    name:
      - make
      - gcc
      - git
    state: present

- name: checkout gaia
  git:
    repo: 'https://github.com/cosmos/gaia.git'
    version: '{{ gaia_version }}'
    clone: yes
    update: yes
    dest: '/tmp/gaia_{{ gaia_version }}'

- name: install gaiad
  shell: 'cd /tmp/gaia_{{ gaia_version }}; make install; cp /root/go/bin/gaiad /usr/local/bin/'
