---
- name: install packages
  apt:
    name:
      - make
      - gcc
      - git
    state: present

- name: checkout gaia
  git:
    repo: 'https://github.com/cosmos/gaia.git'
    version: '{{ gaia_version }}'
    clone: yes
    update: yes
    dest: '/tmp/gaia_{{ gaia_version }}'

- name: install gaiad
  shell: '. /etc/profile.d/go.sh; cd /tmp/gaia_{{ gaia_version }}; make install; cp /root/go/bin/gaiad /usr/local/bin/'

- name: create gaia user
  user:
    name: gaia
    shell: '/bin/bash'
    comment: 'Gaia Service User'

- name: copy README.md
  copy:
    src: 'README.md'
    dest: '/home/gaia/README.md'
    mode: 0644
    owner: 'gaia'
    group: 'gaia'

- name: copy init script
  copy:
    src: '{{ item }}'
    dest: '/home/gaia/{{ item }}'
    mode: 0755
    owner: 'gaia'
    group: 'gaia'
  with_items:
    - gaiad_init.sh
    - gaiad_test_init.sh

- name: copy systemd unit for gaiad
  template:
    src: 'unit.j2'
    dest: '/etc/systemd/system/gaiad.service'
  notify:
    - daemon_reload
    - enable_gaiad

- name: remove no need packages
  apt:
    name:
      - gcc
      - make
      - git
    state: absent


