---
- name: install releaded packages
  apt:
    name:
      - make
      - gcc
      - git
    state: present

- name: Ignore host key checking
  set_fact:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: checkout gaia
  git:
    repo: 'git@github.com:cosmos/gaia.git'
    version: '{{ gaia_version }}'
    clone: yes
    update: yes
    dest: '/tmp/gaia_{{ gaia_version }}'
